import Head from 'next/head'
import { Container, Row } from 'react-bootstrap';
import axios from 'axios';
import CatalogItem from '@/components/catalog/catalog-item';

export default function Home({ payload }) {
  return (
    <>
      <Head>
        <title>Экипировка в наличии</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <h1>Test</h1>
        <hr />
        <Row>
          { payload.map(item => <CatalogItem item={ item } key={ `catalog-item-${ item.id }` } />) }
        </Row>
      </Container>
    </>
  )
}

export async function getServerSideProps() {
  const payload = await axios
    .post(process.env.API_HOST + '/api/v1/public/products')
    .then(({ data }) => {
      console.log(data);
      const { payload = null } = data;
      return payload;
    })
  ;

  return {props: { payload }};
}
